#!/bin/bash -e

# This script will download the latest release of Firefox from Mozilla and package it up into a DEB.
# It takes 2 arguments:
# - ARCH is the architecture of the binary build (amd64 or i386, default amd64)
# - LANG is the language/local of the binary build (default en-GB)
# The DEB files are saved in the same directory as the script.

# USAGE:
# Download the script and make it executable: chmod +x firefox
# Invoke the script like this to build the i386 version in US English language/locale: ./firefox i386 en-US

ARCH="$1"
if [ "$ARCH" != "i386" ]; then
	OS=linux64
	ARCH=amd64
else
	OS=linux
fi

LANG="$2"
if [ "$LANG" == "" ]; then
	LANG=en-GB
fi

URL=$(curl -s "https://download.mozilla.org/?product=firefox-latest-ssl&os=$OS&lang=$LANG" | grep "https://" | cut -d '"' -f 2)
VERSION=$(echo "$URL" | grep -Eom 1 "/([0-9.]+)/" | cut -d "/" -f 2)
echo "================================================================================"
echo "Version      : $VERSION"
echo "Architecture : $ARCH"
echo "Language     : $LANG"
echo "================================================================================"

DIR_TMP=./$ARCH/tmp
DIR_DEB=./$ARCH/DEBIAN
DIR_OPT=./$ARCH/opt
DIR_APP=./$ARCH/usr/share/applications
ARCHIVE=firefox.tar.bz2

rm -rf ./$ARCH
mkdir -p "$DIR_TMP" "$DIR_DEB" "$DIR_OPT" "$DIR_APP"

curl "$URL" > "$DIR_TMP/$ARCHIVE"
tar -C "$DIR_OPT" -xvjf "$DIR_TMP/$ARCHIVE"

rm -rf "$DIR_TMP"

printf "[Desktop Entry]
Name=Firefox
Name[bg]=Firefox
Name[ca]=Firefox
Name[cs]=Firefox
Name[el]=Firefox
Name[es]=Firefox
Name[fa]=Firefox
Name[fi]=Firefox
Name[fr]=Firefox
Name[hu]=Firefox
Name[it]=Firefox
Name[ja]=Firefox
Name[ko]=Firefox
Name[nb]=Firefox
Name[nl]=Firefox
Name[nn]=Firefox
Name[no]=Firefox
Name[pl]=Firefox
Name[pt]=Firefox
Name[pt_BR]=Firefox
Name[ru]=Firefox
Name[sk]=Firefox
Name[sv]=Firefox
Comment=Browse the World Wide Web
Comment[bg]=Сърфиране в Мрежата
Comment[ca]=Navegueu per el web
Comment[cs]=Prohlížení stránek World Wide Webu
Comment[de]=Im Internet surfen
Comment[el]=Περιηγηθείτε στον παγκόσμιο ιστό
Comment[es]=Navegue por la web
Comment[fa]=صفحات شبکه جهانی اینترنت را مرور نمایید
Comment[fi]=Selaa Internetin WWW-sivuja
Comment[fr]=Navigue sur Internet
Comment[hu]=A világháló böngészése
Comment[it]=Esplora il web
Comment[ja]=ウェブを閲覧します
Comment[ko]=웹을 돌아 다닙니다
Comment[nb]=Surf på nettet
Comment[nl]=Verken het internet
Comment[nn]=Surf på nettet
Comment[no]=Surf på nettet
Comment[pl]=Przeglądanie stron WWW 
Comment[pt]=Navegue na Internet
Comment[pt_BR]=Navegue na Internet
Comment[ru]=Обозреватель Всемирной Паутины
Comment[sk]=Prehliadanie internetu
Comment[sv]=Surfa på webben
GenericName=Web Browser
GenericName[bg]=Интернет браузър
GenericName[ca]=Navegador web
GenericName[cs]=Webový prohlížeč
GenericName[de]=Webbrowser
GenericName[el]=Περιηγητής ιστού
GenericName[es]=Navegador web
GenericName[fa]=مرورگر اینترنتی
GenericName[fi]=WWW-selain
GenericName[fr]=Navigateur Web
GenericName[hu]=Webböngésző
GenericName[it]=Browser Web
GenericName[ja]=ウェブ・ブラウザ
GenericName[ko]=웹 브라우저
GenericName[nb]=Nettleser
GenericName[nl]=Webbrowser
GenericName[nn]=Nettlesar
GenericName[no]=Nettleser
GenericName[pl]=Przeglądarka WWW
GenericName[pt]=Navegador Web
GenericName[pt_BR]=Navegador Web
GenericName[ru]=Интернет-браузер
GenericName[sk]=Internetový prehliadač
GenericName[sv]=Webbläsare
X-GNOME-FullName=Firefox Web Browser
X-GNOME-FullName[bg]=Интернет браузър (Firefox)
X-GNOME-FullName[ca]=Navegador web Firefox
X-GNOME-FullName[cs]=Firefox Webový prohlížeč
X-GNOME-FullName[el]=Περιηγήτης Ιστού Firefox
X-GNOME-FullName[es]=Navegador web Firefox
X-GNOME-FullName[fa]=مرورگر اینترنتی Firefox
X-GNOME-FullName[fi]=Firefox-selain
X-GNOME-FullName[fr]=Navigateur Web Firefox
X-GNOME-FullName[hu]=Firefox webböngésző
X-GNOME-FullName[it]=Firefox Browser Web
X-GNOME-FullName[ja]=Firefox ウェブ・ブラウザ
X-GNOME-FullName[ko]=Firefox 웹 브라우저
X-GNOME-FullName[nb]=Firefox Nettleser
X-GNOME-FullName[nl]=Firefox webbrowser
X-GNOME-FullName[nn]=Firefox Nettlesar
X-GNOME-FullName[no]=Firefox Nettleser
X-GNOME-FullName[pl]=Przeglądarka WWW Firefox
X-GNOME-FullName[pt]=Firefox Navegador Web
X-GNOME-FullName[pt_BR]=Navegador Web Firefox
X-GNOME-FullName[ru]=Интернет-браузер Firefox
X-GNOME-FullName[sk]=Internetový prehliadač Firefox
X-GNOME-FullName[sv]=Webbläsaren Firefox
Type=Application
Exec=/opt/firefox/firefox %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/opt/firefox/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Firefox
StartupNotify=true
" > "$DIR_APP/firefox.desktop"

printf "Package: firefox
Version: $VERSION
Architecture: $ARCH
Maintainer: austozi <austozi@outlook.com>
Installed-Size: 232900
Provides: gnome-www-browser, www-browser
Section: web
Priority: optional
Description: The latest release of the Mozilla Firefox web browser. 
 Firefox is a powerful, extensible web browser with support for modern
 web application technologies.
" > "$DIR_DEB/control"

dpkg -b "$ARCH" "./firefox_${VERSION}_${ARCH}.deb"
rm -rf "$ARCH"
